name: 'Test Report'
on:
  workflow_run:
    workflows: ['Dotnet build']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: dotnet-results-3.1.x
        name: Test report
        path: '*.trx'                     # Path to test results (inside artifact .zip)
        reporter: dotnet-trx    